### PR TITLE
feat: add in pre-commit-settings

### PR DESCRIPTION
**Pull request by knechtionscoding**
Signed-off-by: Hans Knecht <Hans.Knecht@missionlane.com>

### CODE REVIEW

**Review by realshuting — COMMENTED** [review]
Thanks @KnechtionsCoding, this looks good!

Can we add a note as we discussed https://github.com/kyverno/kyverno/pull/1673#issuecomment-801262270?

**Comment by knechtionscoding** [comment]
> Thanks @KnechtionsCoding, this looks good!
> 
> Can we add a note as we discussed [kyverno/kyverno#1673 (comment)](https://github.com/kyverno/kyverno/pull/1673#issuecomment-801262270)?

Absolutely. I was just out sick and not feeling well today, I'll finish this up tomorrow.

**Comment by realshuting** [comment]
@KnechtionsCoding - thanks! Hope you feel better now.

**Comment by knechtionscoding** [comment]
@realshuting Take a look now, once this is pushed up, I'll open another PR with an example to show people the basic config required to properly use it.

**Review by realshuting — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
